package com.github.yamin8000.spacetraders_sdk.model.ship

enum class ShipRole {
    FABRICATOR, HARVESTER, HAULER, INTERCEPTOR,
    EXCAVATOR, TRANSPORT, REPAIR, SURVEYOR, COMMAND,
    CARRIER, PATROL, SATELLITE, EXPLORER, REFINERY
}